### ISSUE TITLE
VCD Dump signals/port with different names

### ISSUE THREAD

**Issue by aignacio** [ripopov/gdb_systemc_trace#3]
Hi @ripopov,
tks for the excellent scripting, I have just a small question, can you point me why the signals/ports name are name **port_X** some rather than the name written in the sysc?
ps.: I'm compiling with -g -Og
![Screenshot from 2020-03-17 12-49-16](https://user-images.githubusercontent.com/5991372/76857750-fd51fa00-684d-11ea-91ff-a59b90c1ff82.png)

**Comment by ripopov** [comment]
It uses names that you pass to sc_object constructor, like:
```
sc_signal a_sig{"a_sig"};
sc_in b_in{"b_in"};
```
If name is not initialized from constructor parameter, then SystemC kernel generates names automatically, in form signal_X, port_X.

**Comment by aignacio** [comment]
@ripopov tks for explanation, actually I didn't know that you could give such attributes to sc_obj, do you have a manual for systemc usage to point me?

**Comment by ripopov** [comment]
@aignacio All functions, including constructors are documented in IEEE SystemC standard. I don't know what to recommend as a tutorial. But SystemC uses those object names in error reporting, so you usually quickly learn to pass name explicitly.

In SystemC 2.3.3 there is a convenient macro SC_NAMED that saves from copy-pasting names: 
`sc_signal SC_NAMED( a_sig );  // expands to a_sig( "a_sig" );`

**Comment by aignacio** [comment]
@ripopov tks so much, I used this macro and it's showing as suppose to...
